services:
  postgres:
    build:
      context: .
      dockerfile: src.database.dockerfile
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - db:/data/postgres
    ports:
      - '5432:5432'
    restart: unless-stopped

volumes:
  db:
    external: true
